### ISSUE TITLE
for node dependencies, how to force-trigger `npm i` instead of `npm ci` when package-lock.json present?

### ISSUE THREAD

**Issue by filmaj** [architect/hydrate#21]
my use case as an app writer is: i just went through and updated the dependencies of a bunch (or all) of my functions in my app. i always keep both `package.json` and `package-lock.json` revisioned for all functions. if i run `hydrate.install()`, hydrate will run `npm ci` under the hood - which won't honour the new changes inside `package.json` and instead will install whatever is revisioned inside `package-lock.json`.

do we need a new API to cover this case? i think running `hydrate.update()` is closer, but it may also change other dependencies' versions if there are newer versions, which i may not want.

**Comment by brianleroux** [comment]
good question; sorta comes down to workflow. think if you have defined a `package-lock.json` we should honor that and if it is not present we should run `npm i` and create one… which is to say, if the dev wants us to *not* use `npm ci` then they should remove `package-lock.json` … something like `rm -rf src/**/*/package-lock.json && npx hydrate` would work.

**Comment by filmaj** [comment]
K, fair enough.

**Comment by ryanblock** [comment]
@filmaj to dig a bit deeper on this: `if i run hydrate.install(), hydrate will run npm ci under the hood - which won't honour the new changes inside package.json and instead will install whatever is revisioned inside package-lock.json`

How is this state possible? Did you manually type something into `package.json`, and not run `npm i whatever`? iirc npm throws package-lock-out-of-sync errors when this kind of thing happens and performing `ci` operations.

Understanding how this state is possible may give me some ideas on how to better improve dep hydration though – npm can be fiddly (obvs) but there's almost definitely room to improve in how we automate these operations imo.
